version: '3'
services:
  app_db:
    image: postgres:13
    logging:
      driver: none
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./app-db/.postgresql:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
  app_service:
    build:
      context: ./../
      dockerfile: ./docker/app-service/Dockerfile
      target: runner
    command: sh -c "yarn migrate:up && yarn start:prod"
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - app_db
  app_service_jest:
    build:
      context: ./../
      dockerfile: ./docker/app-service/Dockerfile
      target: jestTest
    depends_on:
      - app_db
