version: '3'
services:
  app_db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./app-db/.postgresql:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
